services:
  ucsc:
    restart: "always"
    network_mode: "host"
    container_name: "ucsc_genomebrowser"
    image: "ghcr.io/ljw20180420/ucsc_genomebrowser_image:latest"
    build:
      context: "https://raw.githubusercontent.com/ucscGenomeBrowser/kent/master/src/product/installer/docker/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - /home/ljw/sdb1/ucsc/hubs/myHub:/usr/local/apache/htdocs/myHub
    command: /sbin/my_init --skip-startup-files
